### ISSUE TITLE
Why the example has no sound

### ISSUE THREAD

**Issue by Lafree317** [LightGive/SimpleSoundManager#1]
Hello, thank you for open source this library.
Why the example has no sound,unity's switch to control the sound is also grey.

**Comment by Lafree317** [comment]
unity version 2018.2.6f1

**Comment by LightGive** [comment]
Thank you for your report.

I did not have a sound in Example because it was copyrighted by BGM and SE, so I kept erasing it, I'm sorry.
I will check it immediately after this.


2018/11/19 13:47、lafreeZhaZha <notifications@github.com<mailto:notifications@github.com>>のメール:


unity version 2018.2.6f1

**Comment by Lafree317** [comment]
Ok, thank you
I'm trying to fix it, and I'll pay attention later

**Comment by LightGive** [comment]
I have taken BGM and SE as examples.

https://www.dropbox.com/s/6z16nkfglorzvj4/SimpleSoundManager%281.1.1%29_IncludeExample.unitypackage?dl=0
Surely delete the "SimpleSoundManager" in the project right now and insert it again. I think this will work.

Also, since it is not what I made, please do not use BGM or SE used in actual game examples.

Currently, when processing is heavy, there are bugs that delay loops such as BGM and SE. Therefore, this manager is for light projects. I am currently correcting it, so I think that it will be fixed soon, but if there is a problem it may be better to use another manager.


2018/11/19 14:13、lafreeZhaZha <notifications@github.com<mailto:notifications@github.com>>のメール:


Ok, thank you
I'm trying to fix it, and I'll pay attention later

**Comment by LightGive** [comment]
I am not good at English, so I am talking through Google Translate. So it may not be well communicated, I am sorry if it is.


2018/11/19 14:13、lafreeZhaZha <notifications@github.com<mailto:notifications@github.com>>のメール:


Ok, thank you
I'm trying to fix it, and I'll pay attention later

**Comment by Lafree317** [comment]
I think I know what the problem is...
This is closed by default after Unity is updated....
<img width="261" alt="3cce5f0a-f42d-4eea-8ab5-e921cf5ca7bf" src="https://user-images.githubusercontent.com/13520567/48688017-16697d00-ebff-11e8-8d06-50e796bfaa47.png">
I was too stupid

**Comment by LightGive** [comment]
lol
